{"name": "test_div_error[case1,除数为0]", "status": "broken", "statusDetails": {"message": "ZeroDivisionError: division by zero", "trace": "self = <homework_pytest.test_calculate.test_calculate.TestCalculate object at 0x7fdb80d020a0>, get_calc = <homework_pytest.calculate.calculate.Calculate object at 0x7fdb80d02490>, get_div_data_error_byfixture = [5, 0, 'ZeroDivisionError']\ntest_picture = None\n\n    @allure.story(\"除法，数据不正确\")\n    @pytest.mark.run(order=1)\n    def test_div_error(self,get_calc,get_div_data_error_byfixture,test_picture):\n>       result = get_calc.div(get_div_data_error_byfixture[0],get_div_data_error_byfixture[1])\n\ntest_calculate.py:70: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <homework_pytest.calculate.calculate.Calculate object at 0x7fdb80d02490>, a = 5, b = 0\n\n    def div(self,a,b):\n>       return a/b\nE       ZeroDivisionError: division by zero\n\n../calculate/calculate.py:10: ZeroDivisionError"}, "parameters": [{"name": "get_div_data_error_byfixture", "value": "[5, 0, 'ZeroDivisionError']"}], "start": 1630920168792, "stop": 1630920168792, "uuid": "ffab253c-af85-4906-9cb9-99c455b5e07a", "historyId": "bb464f215ebb8984a2ef4cc008b48bd1", "testCaseId": "1124a2742ec0e1fdf86698691e882808", "fullName": "test_calculate.TestCalculate#test_div_error", "labels": [{"name": "feature", "value": "计算器"}, {"name": "story", "value": "除法，数据不正确"}, {"name": "tag", "value": "run(order=1)"}, {"name": "suite", "value": "test_calculate"}, {"name": "subSuite", "value": "TestCalculate"}, {"name": "host", "value": "liyongdeMacBook-Pro.local"}, {"name": "thread", "value": "98256-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculate"}]}